"use client";

import * as React from "react";
import Link from "next/link";
import { CourseSyllabus } from "@/services/syllabus-service";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  BookOpen,
  Search,
  Download,
  Sparkles,
  FileText,
  Clock,
  Award,
  Layers,
  ChevronDown,
  ChevronUp,
  CheckCircle2,
  BookMarked,
  GraduationCap,
} from "lucide-react";

interface SyllabusClientViewProps {
  allCourses: CourseSyllabus[];
}

export function SyllabusClientView({ allCourses }: SyllabusClientViewProps) {
  const [selectedSemester, setSelectedSemester] = React.useState<number | "ALL">("ALL");
  const [searchQuery, setSearchQuery] = React.useState("");
  const [expandedCourseId, setExpandedCourseId] = React.useState<string | null>(allCourses[0]?.id || null);
  const [downloadSuccessId, setDownloadSuccessId] = React.useState<string | null>(null);

  // Filter courses by semester and search query
  const filteredCourses = React.useMemo(() => {
    return allCourses.filter((course) => {
      const matchSem = selectedSemester === "ALL" || course.semester === selectedSemester;
      const matchQuery =
        !searchQuery.trim() ||
        course.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        course.courseCode.toLowerCase().includes(searchQuery.toLowerCase()) ||
        course.units.some((u) => u.topics.some((t) => t.toLowerCase().includes(searchQuery.toLowerCase())));
      return matchSem && matchQuery;
    });
  }, [allCourses, selectedSemester, searchQuery]);

  // Real client-side syllabus download handler
  const handleDownloadSyllabus = (course: CourseSyllabus) => {
    const content = `================================================================================
ACCREDITED B.TECH COMPUTER SCIENCE & ENGINEERING CURRICULUM
Course Code: ${course.courseCode} | Course Title: ${course.title}
Semester: ${course.semester} | Credits: ${course.credits} | Lecture Hours: ${course.totalHours} hrs
Category: ${course.category}
================================================================================

COURSE DESCRIPTION:
${course.description}

PREREQUISITES:
${course.prerequisites.join(", ") || "None"}

EXAMINATION EVALUATION WEIGHTAGE:
- Mid-Term Exams: ${course.examWeightage.midTermPercent}%
- End-Term University Exam: ${course.examWeightage.endTermPercent}%
- Internal Assignments & Lab Vivas: ${course.examWeightage.internalAssignmentsPercent}%

================================================================================
UNIT-WISE DETAILED SYLLABUS MODULES:
${course.units
  .map(
    (u) => `
UNIT ${u.unitNumber}: ${u.title.toUpperCase()} (${u.hours} Hours)
${u.topics.map((t, idx) => `  ${idx + 1}. ${t}`).join("\n")}
`
  )
  .join("\n")}
================================================================================
PRESCRIBED REFERENCE TEXTBOOKS:
${course.textbooks.map((b, i) => `${i + 1}. "${b.title}" by ${b.author} (${b.edition})`).join("\n")}

${
  course.labExperiments && course.labExperiments.length > 0
    ? `================================================================================
PRACTICAL LABORATORY EXPERIMENTS:
${course.labExperiments.map((lab, i) => `Lab ${i + 1}: ${lab}`).join("\n")}`
    : ""
}

================================================================================
Generated by CampusFlow — Academic Syllabus & Learning Center
`;

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${course.courseCode}_${course.title.replace(/\s+/g, "_")}_Syllabus.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setDownloadSuccessId(course.id);
    setTimeout(() => setDownloadSuccessId(null), 3000);
  };

  return (
    <div className="space-y-8">
      {/* Header Banner */}
      <div className="p-6 sm:p-8 rounded-3xl bg-gradient-to-r from-blue-50/80 via-indigo-50/60 to-purple-50/80 dark:from-blue-950/40 dark:via-indigo-950/20 dark:to-purple-950/30 border border-blue-200/60 dark:border-blue-900/40 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <Badge variant="purple" className="text-xs">
              B.Tech CSE Curriculum
            </Badge>
            <span className="text-xs text-zinc-500">•</span>
            <span className="text-xs font-semibold text-zinc-600 dark:text-zinc-400">
              Accredited University Syllabus
            </span>
          </div>
          <h1 className="text-2xl sm:text-4xl font-extrabold tracking-tight text-zinc-900 dark:text-zinc-50">
            Course Syllabus & Curriculum Hub
          </h1>
          <p className="text-xs sm:text-sm text-zinc-600 dark:text-zinc-400 max-w-2xl leading-relaxed">
            Access certified semester-wise subject units, examination weightage, prescribed textbook references, and lab experiment guidelines.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Link href="/dashboard/notes">
            <Button variant="outline" className="text-xs gap-1.5 bg-white/80 dark:bg-zinc-900/80">
              <FileText className="w-4 h-4 text-indigo-500" />
              <span>Browse Subject Notes</span>
            </Button>
          </Link>
          <Link href="/dashboard/ai">
            <Button className="bg-indigo-600 hover:bg-indigo-700 text-white text-xs gap-1.5 shadow-md shadow-indigo-500/20">
              <Sparkles className="w-4 h-4" />
              <span>Ask AI About Syllabus</span>
            </Button>
          </Link>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4 p-4 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800 shadow-sm">
        {/* Semester Filter Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 sm:pb-0">
          <button
            type="button"
            onClick={() => setSelectedSemester("ALL")}
            className={`px-3 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
              selectedSemester === "ALL"
                ? "bg-indigo-600 text-white shadow-sm"
                : "bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-200"
            }`}
          >
            All Semesters
          </button>
          {[3, 4, 5, 6, 7, 8].map((sem) => (
            <button
              key={sem}
              type="button"
              onClick={() => setSelectedSemester(sem)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${
                selectedSemester === sem
                  ? "bg-indigo-600 text-white shadow-sm"
                  : "bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-200"
              }`}
            >
              Sem {sem}
            </button>
          ))}
        </div>

        {/* Search input */}
        <div className="relative min-w-[260px]">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-zinc-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search subjects, units, or topics..."
            className="w-full pl-9 pr-4 py-2 rounded-xl text-xs bg-zinc-50 dark:bg-zinc-800/60 border border-zinc-200 dark:border-zinc-700 text-zinc-800 dark:text-zinc-200 placeholder-zinc-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
          />
        </div>
      </div>

      {/* Courses Accordion List */}
      <div className="space-y-5">
        {filteredCourses.length === 0 ? (
          <div className="p-12 text-center rounded-3xl border border-dashed border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-500 space-y-2">
            <BookOpen className="w-10 h-10 mx-auto text-zinc-400 opacity-60" />
            <h3 className="font-bold text-base text-zinc-800 dark:text-zinc-200">
              No matching courses found
            </h3>
            <p className="text-xs">Try selecting a different semester or clearing your search term.</p>
          </div>
        ) : (
          filteredCourses.map((course) => {
            const isExpanded = expandedCourseId === course.id;
            return (
              <Card
                key={course.id}
                className="border-zinc-200/80 dark:border-zinc-800 shadow-sm overflow-hidden transition-all duration-200"
              >
                {/* Course Header Bar */}
                <div
                  onClick={() => setExpandedCourseId(isExpanded ? null : course.id)}
                  className="p-5 sm:p-6 flex flex-col md:flex-row md:items-center justify-between gap-4 cursor-pointer hover:bg-zinc-50/70 dark:hover:bg-zinc-900/60 transition-colors"
                >
                  <div className="flex items-start sm:items-center gap-3.5">
                    <div className="w-12 h-12 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400 font-extrabold text-sm flex items-center justify-center shrink-0 border border-indigo-200/50 dark:border-indigo-900/50">
                      {course.courseCode}
                    </div>
                    <div>
                      <div className="flex items-center gap-2 flex-wrap">
                        <Badge variant="purple" className="text-[10px]">
                          Semester {course.semester}
                        </Badge>
                        <Badge variant="secondary" className="text-[10px]">
                          {course.category}
                        </Badge>
                        <span className="text-xs text-zinc-400">•</span>
                        <span className="text-xs text-zinc-500 font-medium">
                          {course.credits} Credits ({course.totalHours} Lecture Hours)
                        </span>
                      </div>
                      <h3 className="text-lg font-bold text-zinc-900 dark:text-zinc-50 mt-1">
                        {course.title}
                      </h3>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 shrink-0 self-end md:self-center">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDownloadSyllabus(course);
                      }}
                      className="text-xs gap-1.5"
                    >
                      {downloadSuccessId === course.id ? (
                        <>
                          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
                          <span className="text-emerald-600">Saved!</span>
                        </>
                      ) : (
                        <>
                          <Download className="w-3.5 h-3.5" />
                          <span>Download Syllabus</span>
                        </>
                      )}
                    </Button>

                    <Link href={`/dashboard/notes?subject=${encodeURIComponent(course.title)}`} onClick={(e) => e.stopPropagation()}>
                      <Button size="sm" className="bg-indigo-600 hover:bg-indigo-700 text-white text-xs gap-1">
                        <FileText className="w-3.5 h-3.5" />
                        <span>Study Notes</span>
                      </Button>
                    </Link>

                    <button
                      type="button"
                      aria-label="Expand syllabus details"
                      className="w-8 h-8 rounded-full flex items-center justify-center text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200"
                    >
                      {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                    </button>
                  </div>
                </div>

                {/* Expanded Syllabus Breakdown */}
                {isExpanded && (
                  <CardContent className="border-t border-zinc-100 dark:border-zinc-800/80 p-5 sm:p-7 space-y-7 bg-zinc-50/40 dark:bg-zinc-950/40">
                    {/* Course Overview & Exam Weightage */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      <div className="md:col-span-2 p-4 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800 space-y-2">
                        <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-500">
                          Course Objectives & Scope
                        </h4>
                        <p className="text-xs sm:text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed">
                          {course.description}
                        </p>
                      </div>

                      <div className="p-4 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800 space-y-2">
                        <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-500">
                          Exam Evaluation Weightage
                        </h4>
                        <div className="space-y-1.5 text-xs text-zinc-600 dark:text-zinc-400">
                          <div className="flex justify-between font-medium">
                            <span>Mid-Term Exam:</span>
                            <span className="font-bold text-zinc-900 dark:text-zinc-100">{course.examWeightage.midTermPercent}%</span>
                          </div>
                          <div className="flex justify-between font-medium">
                            <span>End-Term Finals:</span>
                            <span className="font-bold text-zinc-900 dark:text-zinc-100">{course.examWeightage.endTermPercent}%</span>
                          </div>
                          <div className="flex justify-between font-medium">
                            <span>Internal Lab/Vivas:</span>
                            <span className="font-bold text-zinc-900 dark:text-zinc-100">{course.examWeightage.internalAssignmentsPercent}%</span>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Unit Modules */}
                    <div className="space-y-4">
                      <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-500 flex items-center gap-2">
                        <Layers className="w-3.5 h-3.5 text-indigo-500" />
                        5 Core Academic Units & Chapters
                      </h4>

                      <div className="grid grid-cols-1 gap-3.5">
                        {course.units.map((unit) => (
                          <div
                            key={unit.unitNumber}
                            className="p-4 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800 shadow-sm space-y-2.5"
                          >
                            <div className="flex items-center justify-between gap-3">
                              <div className="flex items-center gap-2.5">
                                <span className="w-6 h-6 rounded-lg bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 font-bold text-xs flex items-center justify-center">
                                  U{unit.unitNumber}
                                </span>
                                <h5 className="font-bold text-sm text-zinc-900 dark:text-zinc-100">
                                  {unit.title}
                                </h5>
                              </div>
                              <span className="text-xs font-semibold text-zinc-400">
                                {unit.hours} Hours
                              </span>
                            </div>

                            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
                              {unit.topics.map((t, idx) => (
                                <li
                                  key={idx}
                                  className="text-xs text-zinc-600 dark:text-zinc-400 flex items-start gap-2"
                                >
                                  <span className="text-indigo-500 mt-0.5">•</span>
                                  <span>{t}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Reference Textbooks & Lab Experiments */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {/* Books */}
                      <div className="p-4 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800 space-y-2.5">
                        <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-500 flex items-center gap-1.5">
                          <BookMarked className="w-3.5 h-3.5 text-indigo-500" />
                          Recommended Textbooks
                        </h4>
                        <div className="space-y-2">
                          {course.textbooks.map((book, bIdx) => (
                            <div key={bIdx} className="text-xs text-zinc-700 dark:text-zinc-300">
                              <p className="font-semibold text-zinc-900 dark:text-zinc-100">
                                {bIdx + 1}. {book.title}
                              </p>
                              <p className="text-[11px] text-zinc-500">
                                By {book.author} — {book.edition}
                              </p>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Lab Experiments */}
                      {course.labExperiments && (
                        <div className="p-4 rounded-2xl bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800 space-y-2.5">
                          <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-500 flex items-center gap-1.5">
                            <Award className="w-3.5 h-3.5 text-emerald-500" />
                            Practical Lab Practicals
                          </h4>
                          <ul className="space-y-1.5">
                            {course.labExperiments.slice(0, 4).map((lab, lIdx) => (
                              <li key={lIdx} className="text-xs text-zinc-600 dark:text-zinc-400 flex items-start gap-1.5">
                                <span className="text-emerald-500 font-bold">✓</span>
                                <span>{lab}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </CardContent>
                )}
              </Card>
            );
          })
        )}
      </div>
    </div>
  );
}
