"use client";

import * as React from "react";
import Link from "next/link";
import { NoteItem } from "@/services/notes-service";
import { NoteStatus, NOTE_STATUSES } from "@/schemas/notes";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  X,
  FileText,
  Sparkles,
  Download,
  Calendar,
  Tag,
  CheckCircle2,
  Clock,
  BookOpen,
  Archive,
  ExternalLink,
  BookMarked,
  Printer,
  HelpCircle,
  ListOrdered,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

interface NotePreviewModalProps {
  note: NoteItem | null;
  isOpen: boolean;
  onClose: () => void;
  onStatusChange: (id: string, status: NoteStatus) => void;
  onToggleArchive: (id: string) => void;
}

export function NotePreviewModal({
  note,
  isOpen,
  onClose,
  onStatusChange,
  onToggleArchive,
}: NotePreviewModalProps) {
  const [activeTab, setActiveTab] = React.useState<"notes" | "syllabus" | "viva">("notes");
  const [openVivaIndex, setOpenVivaIndex] = React.useState<number | null>(0);
  const [downloadSuccess, setDownloadSuccess] = React.useState(false);

  if (!isOpen || !note) return null;

  const formattedDate = new Date(note.createdAt).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  const formatSize = (bytes: number | null) => {
    if (!bytes) return "4.2 MB";
    const mb = bytes / (1024 * 1024);
    if (mb >= 1) return `${mb.toFixed(1)} MB`;
    return `${Math.round(bytes / 1024)} KB`;
  };

  // Real client-side notes download handler
  const handleDownloadNotes = () => {
    const textContent = `================================================================================
CAMPUSFLOW ACADEMIC STUDY NOTES & SYLLABUS REFERENCE
Course/Subject: ${note.subject}
Title: ${note.title}
Category: ${note.category} | Added: ${formattedDate}
Tags: ${note.tags.join(", ")}
================================================================================

SUMMARY & OVERVIEW:
${note.description || "N/A"}

================================================================================
SYLLABUS TOPICS COVERED:
${(note.syllabusTopics || ["Unit Core Curriculum Topics"]).map((t, i) => `${i + 1}. ${t}`).join("\n")}

================================================================================
FULL LECTURE STUDY NOTES:
${note.fullNotesText || "Detailed study notes available in CampusFlow Reader."}

================================================================================
UNIVERSITY EXAM & VIVA QUESTIONS:
${(note.vivaQuestions || [])
  .map(
    (v, i) =>
      `Q${i + 1}: ${v.question}\nAns: ${v.answer}${v.tip ? `\n[Examiner Tip: ${v.tip}]` : ""}\n`
  )
  .join("\n")}
================================================================================
Generated by CampusFlow — One platform for your college life, learning and career.
`;

    const blob = new Blob([textContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${note.fileName ? note.fileName.replace(/\.pdf$/, "") : note.title}_StudyNotes.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 md:p-6 bg-zinc-950/80 backdrop-blur-md animate-in fade-in duration-150">
      <div className="w-full max-w-5xl bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 shadow-2xl overflow-hidden max-h-[94vh] flex flex-col">
        {/* Header Bar */}
        <div className="px-5 py-4 border-b border-zinc-200 dark:border-zinc-800 flex items-center justify-between gap-4 bg-zinc-50/50 dark:bg-zinc-900/50">
          <div className="flex items-center gap-3 min-w-0">
            <div className="w-10 h-10 rounded-xl bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 flex items-center justify-center shrink-0 border border-indigo-500/20">
              <BookOpen className="w-5 h-5" />
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400">
                  {note.subject}
                </span>
                <span className="text-zinc-300 dark:text-zinc-700">•</span>
                <Badge variant="secondary" className="text-[10px]">
                  {note.category}
                </Badge>
                <span className="text-zinc-300 dark:text-zinc-700">•</span>
                <span className="text-xs text-zinc-500">{formatSize(note.fileSize)}</span>
              </div>
              <h2 className="text-base sm:text-lg font-bold text-zinc-900 dark:text-zinc-100 truncate mt-0.5">
                {note.title}
              </h2>
            </div>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            {/* Download Button */}
            <Button
              size="sm"
              onClick={handleDownloadNotes}
              className={`text-xs gap-1.5 transition-all ${
                downloadSuccess
                  ? "bg-emerald-600 hover:bg-emerald-700 text-white"
                  : "bg-zinc-900 hover:bg-zinc-800 dark:bg-zinc-100 dark:hover:bg-white text-white dark:text-zinc-900"
              }`}
            >
              {downloadSuccess ? (
                <>
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  <span>Downloaded!</span>
                </>
              ) : (
                <>
                  <Download className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Download Notes</span>
                </>
              )}
            </Button>

            {/* Ask AI grounding button */}
            <Link href={`/dashboard/ai?noteId=${note.id}`}>
              <Button
                size="sm"
                className="bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white shadow-md shadow-purple-500/20 text-xs gap-1.5"
              >
                <Sparkles className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">Ask AI Assistant</span>
              </Button>
            </Link>

            <button
              type="button"
              onClick={onClose}
              aria-label="Close document viewer"
              className="w-8 h-8 rounded-full flex items-center justify-center text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200 hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Tab Navigation Pill Bar */}
        <div className="px-6 py-2.5 bg-zinc-100/60 dark:bg-zinc-950/60 border-b border-zinc-200/80 dark:border-zinc-800 flex items-center justify-between gap-4 overflow-x-auto">
          <div className="flex items-center gap-1.5">
            <button
              type="button"
              onClick={() => setActiveTab("notes")}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all ${
                activeTab === "notes"
                  ? "bg-white dark:bg-zinc-800 text-indigo-600 dark:text-indigo-400 shadow-sm border border-zinc-200/60 dark:border-zinc-700"
                  : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-200"
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>📖 Full Lecture Notes</span>
            </button>

            <button
              type="button"
              onClick={() => setActiveTab("syllabus")}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all ${
                activeTab === "syllabus"
                  ? "bg-white dark:bg-zinc-800 text-indigo-600 dark:text-indigo-400 shadow-sm border border-zinc-200/60 dark:border-zinc-700"
                  : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-200"
              }`}
            >
              <ListOrdered className="w-3.5 h-3.5" />
              <span>📑 Syllabus Outline</span>
            </button>

            <button
              type="button"
              onClick={() => setActiveTab("viva")}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all ${
                activeTab === "viva"
                  ? "bg-white dark:bg-zinc-800 text-indigo-600 dark:text-indigo-400 shadow-sm border border-zinc-200/60 dark:border-zinc-700"
                  : "text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-200"
              }`}
            >
              <HelpCircle className="w-3.5 h-3.5" />
              <span>💡 Exam & Viva Questions ({note.vivaQuestions?.length || 3})</span>
            </button>
          </div>

          <div className="flex items-center gap-2 text-xs shrink-0">
            <span className="text-zinc-400 text-[11px]">Status:</span>
            <select
              value={note.status}
              onChange={(e) => onStatusChange(note.id, e.target.value as NoteStatus)}
              aria-label="Change status in preview"
              className="font-semibold text-xs bg-zinc-200/60 dark:bg-zinc-800 rounded-lg px-2 py-1 text-zinc-800 dark:text-zinc-200 focus:outline-none cursor-pointer"
            >
              {NOTE_STATUSES.map((st) => (
                <option key={st} value={st} className="bg-white dark:bg-zinc-900">
                  {st.replace("_", " ")}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* Modal Main Reader Area */}
        <div className="flex-1 overflow-y-auto p-5 sm:p-7 space-y-6">
          {/* TAB 1: FULL LECTURE NOTES (READING MODE) */}
          {activeTab === "notes" && (
            <div className="space-y-6 max-w-4xl mx-auto">
              {/* Summary Banner */}
              {note.description && (
                <div className="p-4 sm:p-5 rounded-2xl bg-gradient-to-r from-indigo-50/80 to-purple-50/60 dark:from-indigo-950/30 dark:to-purple-950/20 border border-indigo-100 dark:border-indigo-900/40">
                  <div className="flex items-center gap-2 text-xs font-bold text-indigo-600 dark:text-indigo-400 uppercase tracking-wider mb-1.5">
                    <Sparkles className="w-3.5 h-3.5" />
                    Chapter Objectives & Executive Summary
                  </div>
                  <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed">
                    {note.description}
                  </p>
                  <div className="flex items-center gap-2 mt-3 flex-wrap">
                    {note.tags.map((t) => (
                      <span
                        key={t}
                        className="text-[11px] font-medium px-2 py-0.5 rounded-md bg-white/80 dark:bg-zinc-800/80 border border-zinc-200/60 dark:border-zinc-700 text-zinc-600 dark:text-zinc-300"
                      >
                        #{t}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Study Content Formatted Markdown */}
              <div className="p-6 sm:p-8 rounded-2xl bg-white dark:bg-zinc-900/90 border border-zinc-200 dark:border-zinc-800 shadow-sm space-y-6">
                <article className="prose dark:prose-invert max-w-none text-zinc-800 dark:text-zinc-200">
                  <div className="whitespace-pre-wrap font-sans text-sm leading-relaxed space-y-4">
                    {note.fullNotesText ? (
                      <div className="font-mono text-xs sm:text-sm bg-zinc-50 dark:bg-zinc-950 p-5 rounded-xl border border-zinc-200 dark:border-zinc-800 overflow-x-auto text-zinc-800 dark:text-zinc-200 whitespace-pre-wrap">
                        {note.fullNotesText}
                      </div>
                    ) : (
                      <p className="text-sm text-zinc-500 italic">
                        Detailed study text is being processed by the AI RAG engine.
                      </p>
                    )}
                  </div>
                </article>
              </div>
            </div>
          )}

          {/* TAB 2: SYLLABUS OUTLINE */}
          {activeTab === "syllabus" && (
            <div className="max-w-4xl mx-auto space-y-6">
              <div className="p-5 rounded-2xl bg-zinc-50 dark:bg-zinc-800/40 border border-zinc-200/80 dark:border-zinc-800 space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-base font-bold text-zinc-900 dark:text-zinc-100">
                      Official Subject Syllabus Topics
                    </h3>
                    <p className="text-xs text-zinc-500 mt-0.5">
                      Curriculum modules aligned with accredited university university exams.
                    </p>
                  </div>
                  <Link href="/dashboard/syllabus">
                    <Button size="sm" variant="outline" className="text-xs gap-1">
                      <span>View Full Semester Syllabus</span>
                      <ExternalLink className="w-3 h-3" />
                    </Button>
                  </Link>
                </div>

                <div className="space-y-3 pt-2">
                  {(note.syllabusTopics || [
                    "Module 1: Fundamental Concepts & Architecture",
                    "Module 2: Core Algorithms & Theoretical Proofs",
                    "Module 3: Industry Applications & Modern Optimizations",
                  ]).map((topic, index) => (
                    <div
                      key={index}
                      className="p-3.5 rounded-xl bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800 flex items-start gap-3"
                    >
                      <div className="w-6 h-6 rounded-lg bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">
                        {index + 1}
                      </div>
                      <div className="text-xs sm:text-sm font-medium text-zinc-800 dark:text-zinc-200">
                        {topic}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: VIVA & EXAM QUESTIONS */}
          {activeTab === "viva" && (
            <div className="max-w-4xl mx-auto space-y-4">
              <div className="p-4 rounded-xl bg-amber-50/60 dark:bg-amber-950/20 border border-amber-200/60 dark:border-amber-900/40 text-xs text-amber-800 dark:text-amber-300">
                💡 <b>Top University Exam & Viva Questions:</b> Curated questions frequently asked in semester finals, lab vivas, and technical placements.
              </div>

              <div className="space-y-3">
                {(note.vivaQuestions || [
                  {
                    question: "What are the core concepts covered in this chapter?",
                    answer:
                      "This chapter covers the fundamental architecture, formal definitions, time/space complexity trade-offs, and standard edge cases encountered in real-world software engineering systems.",
                    tip: "Always structure your answer with: Definition -> Real-world Example -> Complexity.",
                  },
                ]).map((item, idx) => {
                  const isOpen = openVivaIndex === idx;
                  return (
                    <div
                      key={idx}
                      className="rounded-2xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 overflow-hidden"
                    >
                      <button
                        type="button"
                        onClick={() => setOpenVivaIndex(isOpen ? null : idx)}
                        className="w-full p-4 text-left flex items-center justify-between gap-3 hover:bg-zinc-50 dark:hover:bg-zinc-800/40 transition-colors"
                      >
                        <span className="text-xs sm:text-sm font-bold text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
                          <span className="text-indigo-600 dark:text-indigo-400">Q{idx + 1}.</span>
                          {item.question}
                        </span>
                        {isOpen ? (
                          <ChevronUp className="w-4 h-4 text-zinc-400 shrink-0" />
                        ) : (
                          <ChevronDown className="w-4 h-4 text-zinc-400 shrink-0" />
                        )}
                      </button>

                      {isOpen && (
                        <div className="px-4 pb-4 pt-1 border-t border-zinc-100 dark:border-zinc-800/60 text-xs sm:text-sm space-y-2 bg-zinc-50/50 dark:bg-zinc-900/40">
                          <p className="text-zinc-700 dark:text-zinc-300 leading-relaxed font-sans">
                            {item.answer}
                          </p>
                          {item.tip && (
                            <div className="text-[11px] text-indigo-600 dark:text-indigo-400 font-semibold bg-indigo-50/60 dark:bg-indigo-950/40 px-3 py-1.5 rounded-lg border border-indigo-100 dark:border-indigo-900/30">
                              🎓 Examiner Tip: {item.tip}
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        {/* Modal Footer Controls */}
        <div className="px-6 py-3.5 border-t border-zinc-200 dark:border-zinc-800 flex items-center justify-between bg-zinc-50/60 dark:bg-zinc-900/60">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => onToggleArchive(note.id)}
            className="text-xs text-zinc-500 hover:text-amber-600 gap-1.5"
          >
            <Archive className="w-4 h-4" />
            <span>{note.isArchived ? "Unarchive Note" : "Archive Note"}</span>
          </Button>

          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownloadNotes}
              className="text-xs gap-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Text/Notes</span>
            </Button>
            <Button size="sm" onClick={onClose} className="text-xs">
              Close Reader
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
